# Generated by Django 5.0.7 on 2024-07-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='details',
        ),
    ]
